@startuml desarrollo_implementacion
package "  "  as usantatecla.tictactoe {
}
package "  "  as usantatecla.tictactoe.models {
}
package "  "  as usantatecla.tictactoe.views {
}
package "  "  as usantatecla.tictactoe.views.console {
}
package "  "  as usantatecla.tictactoe.views.graphics {
}
package "  "  as usantatecla.utils {
}
package "  "  as java.io {
}
package "  "  as java.util {
}
package "  "  as java.awt{
}
package "  "  as java.awt.event{
}
package "  "  as javax.swing{
}

[tictactoe.jar] as jar

jar *--> usantatecla.tictactoe
jar *--> usantatecla.tictactoe.models
jar *--> usantatecla.tictactoe.views
jar *--> usantatecla.tictactoe.views.console
jar *--> usantatecla.tictactoe.views.graphics
jar *--> usantatecla.utils
jar *--> java.io
jar *--> java.util
jar *--> java.awt
jar *--> java.awt.event
jar *--> javax.swing
@enduml

@startuml despliegue_fisica
node node #DDDDDD [
<b>Personal Computer</b>
----
]

[ tictactoe.jar ] as component

node *--> component
@enduml
